name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin || exit 1
      - run: docker build -t bhcir/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true bhcir/react-test npm test

      - run: docker build -t bhcir/multi-client ./client
      - run: docker build -t bhcir/multi-nginx ./nginx
      - run: docker build -t bhcir/multi-server ./server
      - run: docker build -t bhcir/multi-worker ./worker

      - run: docker push bhcir/multi-client
      - run: docker push bhcir/multi-nginx
      - run: docker push bhcir/multi-server
      - run: docker push bhcir/multi-worker

